# Generated by Django 4.1.5 on 2023-03-21 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReviewAPI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='code',
            field=models.CharField(default='generate_unique_code', max_length=8, unique=True),
        ),
    ]
