# Generated by Django 4.1.5 on 2023-03-25 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReviewAPI', '0004_alter_review_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='publisher',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
